import 'dotenv/config'; import express from'express'; import helmet from'helmet'; import cookieParser from'cookie-parser'; import rateLimit from'express-rate-limit'; import bcrypt from'bcryptjs'; import jwt from'jsonwebtoken'; import pg from'pg'; import fs from'fs';
const app=express(),{Pool}=pg,PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET,pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}); if(!SECRET)throw Error('JWT_SECRET required');
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'100kb'}));app.use(cookieParser());app.use('/api',rateLimit({windowMs:60000,limit:120}));app.use(express.static('public'));
const clean=v=>String(v??'').trim(), tok=u=>jwt.sign({id:u.id,role:u.role},SECRET,{expiresIn:'7d'}); function auth(req,res,next){try{req.user=jwt.verify(req.cookies.vowsi_session,SECRET);next()}catch{return res.status(401).json({error:'Sign in required'})}}; function age(d){let b=new Date(d),n=new Date(),a=n.getFullYear()-b.getFullYear();if(n<new Date(n.getFullYear(),b.getMonth(),b.getDate()))a--;return a}
app.post('/api/signup',async(req,res)=>{try{let{email,password,displayName,birthDate,country}=req.body;if(!email||!password||!displayName||!birthDate||!country)return res.status(400).json({error:'Complete all fields'});if(age(birthDate)<18)return res.status(400).json({error:'VOWSI is 18+ only'});if(password.length<10)return res.status(400).json({error:'Password must be 10+ characters'});let role=clean(email).toLowerCase()===clean(process.env.ADMIN_EMAIL).toLowerCase()?'admin':'user',hash=await bcrypt.hash(password,12),q=await pool.query('INSERT INTO users(email,password_hash,display_name,birth_date,country,role) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,email,display_name,role',[clean(email).toLowerCase(),hash,clean(displayName),birthDate,clean(country),role]),u=q.rows[0];res.cookie('vowsi_session',tok(u),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000});res.json({user:u})}catch(e){res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'Account already exists':'Could not create account'})}});
app.post('/api/login',async(req,res)=>{let q=await pool.query('SELECT * FROM users WHERE email=$1',[clean(req.body.email).toLowerCase()]),u=q.rows[0];if(!u||u.is_suspended||!await bcrypt.compare(String(req.body.password||''),u.password_hash))return res.status(401).json({error:'Email or password is incorrect'});res.cookie('vowsi_session',tok(u),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000});res.json({ok:true})});
app.post('/api/logout',(req,res)=>{res.clearCookie('vowsi_session');res.json({ok:true})});app.get('/api/me',auth,async(req,res)=>{let q=await pool.query('SELECT id,email,display_name,birth_date,country,city,languages,relationship_goal,bio,photo_url,role FROM users WHERE id=$1',[req.user.id]);res.json(q.rows[0])});
app.put('/api/profile',auth,async(req,res)=>{let p=req.body,q=await pool.query('UPDATE users SET display_name=$1,country=$2,city=$3,languages=$4,relationship_goal=$5,bio=$6,photo_url=$7 WHERE id=$8 RETURNING *',[clean(p.displayName),clean(p.country),clean(p.city),clean(p.languages),clean(p.relationshipGoal),clean(p.bio).slice(0,800),clean(p.photoUrl),req.user.id]);res.json(q.rows[0])});
app.get('/api/discover',auth,async(req,res)=>{let q=await pool.query(`SELECT id,display_name,EXTRACT(YEAR FROM age(birth_date))::int age,country,city,languages,relationship_goal,bio,photo_url FROM users u WHERE id<>$1 AND NOT is_suspended AND NOT EXISTS(SELECT 1 FROM blocks b WHERE (b.blocker_id=$1 AND b.blocked_id=u.id) OR (b.blocker_id=u.id AND b.blocked_id=$1)) ORDER BY created_at DESC LIMIT 30`,[req.user.id]);res.json(q.rows)});
app.post('/api/like/:id',auth,async(req,res)=>{let o=Number(req.params.id);if(!o||o===req.user.id)return res.status(400).json({error:'Invalid profile'});await pool.query('INSERT INTO likes VALUES($1,$2,NOW()) ON CONFLICT DO NOTHING',[req.user.id,o]);let m=await pool.query('SELECT 1 FROM likes WHERE liker_id=$1 AND liked_id=$2',[o,req.user.id]);if(m.rowCount){let a=Math.min(req.user.id,o),b=Math.max(req.user.id,o),q=await pool.query('INSERT INTO matches(user1_id,user2_id) VALUES($1,$2) ON CONFLICT(user1_id,user2_id) DO UPDATE SET user1_id=EXCLUDED.user1_id RETURNING id',[a,b]);return res.json({matched:true,match:q.rows[0]})}res.json({matched:false})});
app.get('/api/matches',auth,async(req,res)=>{let q=await pool.query(`SELECT m.id match_id,u.id,u.display_name,u.country,u.photo_url FROM matches m JOIN users u ON u.id=CASE WHEN m.user1_id=$1 THEN m.user2_id ELSE m.user1_id END WHERE m.user1_id=$1 OR m.user2_id=$1 ORDER BY m.created_at DESC`,[req.user.id]);res.json(q.rows)});async function owns(u,m){return (await pool.query('SELECT 1 FROM matches WHERE id=$1 AND (user1_id=$2 OR user2_id=$2)',[m,u])).rowCount>0}
app.get('/api/messages/:m',auth,async(req,res)=>{let m=Number(req.params.m);if(!await owns(req.user.id,m))return res.status(403).json({error:'Forbidden'});res.json((await pool.query('SELECT messages.*,users.display_name sender FROM messages JOIN users ON users.id=sender_id WHERE match_id=$1 ORDER BY created_at',[m])).rows)});app.post('/api/messages/:m',auth,async(req,res)=>{let m=Number(req.params.m),body=clean(req.body.body);if(!await owns(req.user.id,m))return res.status(403).json({error:'Forbidden'});if(!body||body.length>2000)return res.status(400).json({error:'Invalid message'});res.json((await pool.query('INSERT INTO messages(match_id,sender_id,body) VALUES($1,$2,$3) RETURNING *',[m,req.user.id,body])).rows[0])});
app.post('/api/block/:id',auth,async(req,res)=>{await pool.query('INSERT INTO blocks VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.id,Number(req.params.id)]);res.json({ok:true})});app.post('/api/report/:id',auth,async(req,res)=>{let reason=clean(req.body.reason).slice(0,500);if(!reason)return res.status(400).json({error:'Reason required'});await pool.query('INSERT INTO reports(reporter_id,reported_id,reason) VALUES($1,$2,$3)',[req.user.id,Number(req.params.id),reason]);res.json({ok:true})});
app.get('*',(req,res)=>res.sendFile(process.cwd()+'/public/index.html'));pool.query(fs.readFileSync('schema.sql','utf8')).then(()=>app.listen(PORT,()=>console.log('VOWSI running on '+PORT)));
